[postgres]
USER = "postgresql://postgres.orvtwqtidvqghblfyhya:[YOUR-PASSWORD]@aws-1-sa-east-1.pooler.supabase.com:5432/postgres"
PASSWORD = "Kevin923079"
HOST = "aws-1-sa-east-1.pooler.supabase.com"
PORT = "5432"

DBNAME = "postgres"
